export const DAYOVA_DESIGN_SYSTEM = {
	brand: {
		attributes: ["structured", "clear", "trustworthy", "supportive", "calm"],
		direction:
			"Modern EdTech look with solid colors, bold systems, quiet hierarchy, and at most one gradient per view.",
	},
	colors: {
		primary: "#00BAFF",
		onPrimary: "#1A1A1A",
		primaryStrong: "#00A0E6",
		primaryAccent: "#4FD8FF",
		buttonNeutral: "#1A1A1A",
		secondary: "#AF52DE",
		text: "#1A1A1A",
		secondaryText: "#697586",
		background: "#F6F6F4",
		appBackground: "#F6F6F4",
		surface: "#FFFFFF",
		light1: "#FFFFFF",
		light2: "#F3F6FA",
		light3: "#FAFAFC",
		mutedSurface: "#F3F6FA",
		border: "#DCE6EE",
		success: "#34C759",
		successSubtle: "#EAFFF1",
		wrong: "#FF9500",
		wrongSubtle: "#FFECD6",
		destructive: "#FF3B30",
		info: "#C9A100",
		infoSubtle: "#FFF8CC",
		system: "#00BAFF",
		systemSubtle: "#F1F7FB",
		theorie: "#5856D6",
		theorieSubtle: "#EEECFF",
		ueben: "#AF52DE",
		uebenSubtle: "#F4ECFF",
		praxis: "#00C7BE",
		praxisSubtle: "#E7FBF6",
		hausaufgabe: "#B88AAE",
		hausaufgabeSubtle: "#F3E8F0",
		path1: "#D7DCE3",
		path2: "#D7DCE3",
		path3: "#8A8D92",
		path4: "#697586",
		path5: "#00A0E6",
		path6: "#00BAFF",
		path7: "#4FD8FF",
		pathLockedBase: "#ADB3BC",
		uploadArtworkBorder: "#DFE4EB",
		uploadArtworkIconBackground: "#F6F8FF",
		uploadArtworkIconBorder: "#D9E2F3",
		uploadArtworkIconFill: "#DFE7F7",
		uploadArtworkIconMuted: "#D7DFF1",
		uploadArtworkShadow: "#8896C8",
	},
	gradients: {
		primaryInteractive: {
			colors: ["#00A0E6", "#4FD8FF"],
			start: { x: 0.5, y: 0 },
			end: { x: 0.5, y: 1 },
		},
	},
	typography: {
		fontFamily: "Poppins",
		display: {
			counter: { fontSize: 60, lineHeight: 68, fontWeight: "600" },
		},
		headline: {
			h1: { fontSize: 32, lineHeight: 48, fontWeight: "600" },
			h2: { fontSize: 24, lineHeight: 36, fontWeight: "600" },
		},
		body: {
			xl: { fontSize: 20, lineHeight: 30, fontWeight: "400" },
			xlSemibold: { fontSize: 20, lineHeight: 30, fontWeight: "600" },
			lg: { fontSize: 16, lineHeight: 24, fontWeight: "400" },
			lgSemibold: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
			md: { fontSize: 14, lineHeight: 21, fontWeight: "400" },
			mdSemibold: { fontSize: 14, lineHeight: 21, fontWeight: "600" },
			sm: { fontSize: 12, lineHeight: 18, fontWeight: "400" },
			smSemibold: { fontSize: 12, lineHeight: 18, fontWeight: "600" },
			xs: { fontSize: 10, lineHeight: 15, fontWeight: "400" },
			xsSemibold: { fontSize: 10, lineHeight: 15, fontWeight: "600" },
		},
		button: {
			default: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
			small: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
		},
		field: {
			placeholder: { fontSize: 16, lineHeight: 24 },
			label: { fontSize: 12, lineHeight: 18 },
			description: { fontSize: 12, lineHeight: 18 },
		},
	},
	radius: {
		infoSmallBox: 24,
		rectangle: 32,
		button: 44,
		input: 32,
	},
	size: {
		button: {
			borderWidth: 0.3,
			defaultHeight: 56,
		},
	},
} as const;
